#!/bin/bash
# Quick reference commands for running the Graph UI application

echo "=========================================="
echo "Graph UI - React Frontend Setup"
echo "=========================================="
echo ""
echo "OPTION 1: Run both servers in parallel"
echo "-----------------------------------------"
echo "Terminal 1 (React):"
echo "  cd graph-ui && npm run dev"
echo ""
echo "Terminal 2 (Flask):"
echo "  python3 graph_web_ui.py"
echo ""
echo "Then open: http://localhost:5173"
echo ""

echo "OPTION 2: Start Flask server"
echo "-----------------------------------------"
echo "  python3 graph_web_ui.py"
echo "  Available at: http://127.0.0.1:5000"
echo ""

echo "OPTION 3: Start React dev server"
echo "-----------------------------------------"
echo "  cd graph-ui && npm run dev"
echo "  Available at: http://localhost:5173"
echo ""

echo "BUILD FOR PRODUCTION"
echo "-----------------------------------------"
echo "  cd graph-ui && npm run build"
echo "  Output in: graph-ui/dist/"
echo ""

echo "INSTALL DEPENDENCIES"
echo "-----------------------------------------"
echo "  cd graph-ui && npm install"
echo ""

echo "PROJECT STRUCTURE"
echo "-----------------------------------------"
echo "  graph-ui/"
echo "  ├── src/"
echo "  │   ├── components/     (React components)"
echo "  │   ├── services/       (API client)"
echo "  │   ├── store/          (Zustand state)"
echo "  │   ├── App.jsx         (Main layout)"
echo "  │   └── index.css       (Global styles)"
echo "  ├── package.json"
echo "  └── vite.config.js"
echo ""

echo "NATURAL LANGUAGE EXAMPLES"
echo "-----------------------------------------"
echo "  'add node Alice'"
echo "  'connect Alice to Bob'"
echo "  'path from Alice to Bob'"
echo "  'BFS from Alice'"
echo "  'list nodes'"
echo "  'delete node Alice'"
echo ""

echo "API ENDPOINTS"
echo "-----------------------------------------"
echo "  GET    /api/graph/nodes"
echo "  GET    /api/graph/visualization"
echo "  GET    /api/graph/stats"
echo "  POST   /api/graph/node"
echo "  PUT    /api/graph/node/{id}"
echo "  DELETE /api/graph/node/{id}"
echo "  POST   /api/graph/edge"
echo "  POST   /api/graph/shortest_path"
echo "  POST   /api/graph/bfs"
echo ""

echo "DOCUMENTATION"
echo "-----------------------------------------"
echo "  See: REACT_SETUP.md"
echo "  See: graph-ui/README.md"
echo ""
